version: "3.3"
services:
    postgres:
        image: postgres:13.3
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
        ports:
            - "5432:${POSTGRES_PORT}"
        volumes:
            - ./dataDB:/var/lib/postgresql/data
    backend:
        environment:
            BACKEND_PORT: ${BACKEND_PORT}
            JWT_SECRET: ${JWT_SECRET}
            JWT_EXPIRESIN: ${JWT_EXPIRESIN}
            POSTGRES_HOST: postgres
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
        volumes:
            - ./back/src:/app/src
        build:
            context: ./back
            dockerfile: ./docker/dev.Dockerfile
        depends_on:
            - "postgres"
    frontend:
        environment:
            BURL: "http://backend:${BACKEND_PORT}"
        ports:
            - "5173:5173"
        volumes:
            - ./front/src:/app/src
        build:
            context: ./front
            dockerfile: ./docker/dev.Dockerfile
        depends_on:
            - "backend"
        stdin_open: true
        tty: true