version: "3.3"
services:
    postgres:
        image: postgres:13.3
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_DB: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
        ports:
            - "5432:${PGPORT}"
        volumes:
            - ./dataDB:/var/lib/postgresql/data
    backend:
        image: mimbol/party_music_back:latest
        environment:
            BACKEND_PORT: ${BACKEND_PORT}
            JWT_SECRET: ${JWT_SECRET}
            JWT_EXPIRESIN: ${JWT_EXPIRESIN}
            POSTGRES_HOST: postgres
            POSTGRES_DB: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
        depends_on:
            - "postgres"
    frontend:
        image: mimbol/party_music_front:latest
        environment:
            BURL: "http://backend:${BACKEND_PORT}"
        ports:
            - "5173:5173"
        depends_on:
            - "backend"
        stdin_open: true
        tty: true